import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import { NextUIProvider } from "@nextui-org/system";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <StoreProvider>
            {children}
            <Toaster/>
          </StoreProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
